services:
  world-postgres:
    image: postgres:15-bullseye
    ports:
      - "5432:5432"
    volumes:
      - ./_volumes/postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: world
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 36

  world-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - ./_volumes/pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json # servers configuration
    depends_on:
      - world-postgres

volumes:
  postgres_volume:
  pgadmin_data:
