version: '3.1'

services:

  adminer:
    image: adminer
    ports:
      - 8080:8080

  postgres:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
